Pull request to review
ViktorOneLove/Intelligent-Placer pull request #2
Opened 2022-02-18 17:49 UTC by ViktorOneLove

2022-02-21 19:32 UTC, DariaWelt commented
Так как оставить комментарии непосредственно по изменениям не могу, напишу по пунктам:

1. Первый абзац написан на английском языке, хотя все дальнейшее описание происходит на русском. На мой взгляд, лучше остановиться на чем-то одном. Но допускаю, что английский мог использоваться для введения иностранных читателей в курс дела.
2. README строка 13: Кажется, это не совсем целесообразный способ вывода бинарного результата. Такой вывод удобен человеку, но не машине, которой может понадобиться результат программы. Также в изначальной постановке задачи предполагалось, что умный расстановщик можно вызывать как функцию.
3. README строка 20: Мне кажется, лучше изменить требование так, чтобы оно стало измеримым. Обычно о пересветах и потере информации в тенях судят по гистограмме. Может, сюда подойдет условие на вид гистограммы. Например, ограничение на долю пикселей с значениями >225 и <25
4. README строка 24: говоря о нормали, ты, наверное, подразумевал угол в 0-5 градусов для камеры, у меня такая же ошибка в постановке)
5. README строка 26, 42, 50: в таком случае нужен параметр: количество сантиметров в одном пикселе. Или же необходимо задать величину в пикселях
6. README строка 27, 32, 39: так же необходимо сделать требование измеримым, тут, скорее всего, подойдет ограничение на величину градиента 
8. README строка 38, 48: Кажется, нужно требование, что фотография вертикальная: ширина меньше высоты
9. Запрещены блики на предметах, но ножницы на снимках бликуют. Понятно, что очень непросто сделать фото и без теней, и без бликов. Тогда, может, стоит скорректировать требования.
10. Линейка в наборе возможных предметов дала сильный блик, а в фотографиях для тестирования алгоритма его нет. Так как, насколько я понимаю, тестовый набор для финального результата будет генерироваться из набора предметов, то могут возникнуть проблемы
11. По той же причине выскажу и опасения по поводу требования располагать предметы на листе бумаги, хотя это условие твоей индивидуальной постановки, так что может это и допустимо.

Отмечу аккуратно подготовленный набор данных.

2022-02-23 08:33 UTC, besperspektivnyak reviewed
Ревью сделано

2022-02-23 08:33 UTC, besperspektivnyak commented on README.md
> +- Толщина нарисованной линии не превышает 5мм.
- 2: Лучше придерживаться одного языка в README.md (возможно с дублированием  особо важных моментов на другой).
- 7: Субъективно, мне сложно читать такое сложнопостроенное первое предложение. Я бы упростила или разбила на несколько.
- 26: Учитывая, что это требование к фотографии, наверное стоит указать, что это расстояние при изначальной постановке предметов. Либо указать это расстояние в пикселях на фотографии. Или перенести в пункт "К предметам на поверхности".
- Небольшие опечатки (для красоты README :) ):
13: "поданной"
49: "задается"

2022-02-23 08:33 UTC, besperspektivnyak commented on README.md
>  [Датасет](https://drive.google.com/drive/folders/1tJ5O16u1zSXOTFghZGYCDElBW5bynx61?usp=sharing)
20: "Предметы и поверхность должны быть равномерно и хорошо освещены" - блики на фотографиях из датасета не соответствуют понятию "равномерной освещенности", поскольку они как раз и являются пересвеченной областью.

2022-03-11 15:41 UTC, DariaWelt requested changes
Rewiev сделано. В целом подход хороший, есть много положительных моментов. Но обработку исключительного случая добавить нужно, как и привести в порядок сигнатуру и вызов метода find_paper_and_polygon_contours

2022-03-11 15:41 UTC, DariaWelt commented on intelligent_placer_lib/lib_impl.py
> +    upper_white = [172, 111, 255]
Почему выбран именно этот диапазон цветового тона, а не весь набор 0-179? ведь при значении saturation близком к 0 не важно, какой был Hue.

2022-03-11 15:41 UTC, DariaWelt commented on intelligent_placer_lib/lib_impl.py
> +    min_contour_area = 12_000
Здесь и ниже, кажется, используется абсолютное знание о том, какой величины лист бумаги на изображении. И какого размера может быть многоугольник. Может, нужно как-то в требованиях указать. Или брать в процентном соотношении от размера изображения.

2022-03-11 15:41 UTC, DariaWelt commented on intelligent_placer_lib/lib_impl.py
> +    idx = area_contours.index(max(area_contours))
При пустом листе будет исключение

2022-03-11 15:41 UTC, DariaWelt commented on intelligent_placer_lib/lib_api.py
> +    polygon_contours, paper_contours = lib.find_paper_and_polygon_contours(path_to_img)
вызов функции не совпадает с сигнатурой. Код не запускается: TypeError: find_paper_and_polygon_contours() missing 2 required positional arguments: 'file_name' and 'path_to_save

2022-03-11 21:12 UTC, ViktorOneLove commented on intelligent_placer_lib/lib_api.py
> +    polygon_contours, paper_contours = lib.find_paper_and_polygon_contours(path_to_img)
Действительно, я как-то пропустил этот момент (копипаст ошибка)
Исправил сигнатуру - закоментил сохранение (результаты можно посмотреть в папке pictures/output)

2022-03-12 10:51 UTC, besperspektivnyak reviewed
Честно говоря, замечаний, еще не упомянутых, к коду нет. Все написано здраво, решение хорошее, а главное рабочее. С вышесказанными замечаниями согласна.

2022-03-12 10:51 UTC, besperspektivnyak commented on intelligent_placer_lib/lib_impl.py
> +
Кажется, что для пользователя библиотеки было бы удобно отразить план работы и уже выполненные его пункты в README

2022-03-12 23:08 UTC, Binh9874123 commented
в целом план хороший
Но надо сделать проверку на исключительные

2022-03-13 08:58 UTC, DariaWelt commented on intelligent_placer_lib/lib_impl.py
> +    filter = cv2.inRange(img_hsv, np.array(lower_white), np.array(upper_white))
filter это ключевое слово языка:( на мой взгляд лучше заменить название переменной чем-то другим

2022-03-20 20:44 UTC, DariaWelt approved these changes

2022-03-22 16:51 UTC, merged